@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhhNzYzZTEyLTBiM2YtNDE5ZS05OTEzLTViOTU1NmY4M2FmZCIsInVzZXJOYW1lIjoiQWRtaW4xIiwiZW1haWwiOiIiLCJjcmVhdGVkQXQiOiIyMDI1LTA3LTMxVDA3OjMwOjA3LjgxOFoiLCJpYXQiOjE3NTM5NDkzODAsImV4cCI6MTc1Mzk1MDEwMH0.9X-z2Jc86mKQU7wVxs-k8Mo4nwe_RIBPpbE-TOjkP_s




###
GET http://localhost:5000/api/v1/seeder/userSeeder
Content-Type: application/json



###
POST  http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{     "userName"    : "Admin1",
      "password" : "Admin123!"
}

###
POST  http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{     "userName"    : "TestAdmin1",
      "email" :  "Admin123@gmail.com",
      "password" :  "Admin123!",
      "phone" :  "0895606104423"
}



###
POST  http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{     "userName"    : "Admin1",
      "password" : "Admin123!"
}

###
GET  http://localhost:5000/api/v1/auth/fetch
Content-Type: application/json
Authorization: Bearer {{token}}



###
GET  http://localhost:5000/api/v1/product/get-all-product
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET  http://localhost:5000/api/v1/product/get-product/3954cd26-4b55-4edf-9aba-7641e41f2712
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST  http://localhost:5000/api/v1/product/get-product/create-product
Content-Type: application/json
Authorization: Bearer {{token}}


###
PUT  http://localhost:5000/api/v1/product/get-product/update-product/b7387bd2-472f-4fb5-b0f7-6d27553de7ba
Content-Type: application/json
Authorization: Bearer {{token}}


###
DELETE  http://localhost:5000/api/v1/product/delete-product/b7387bd2-472f-4fb5-b0f7-6d27553de7ba
Content-Type: application/json
Authorization: Bearer {{token}}





