@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhhNzYzZTEyLTBiM2YtNDE5ZS05OTEzLTViOTU1NmY4M2FmZCIsInVzZXJOYW1lIjoiQWRtaW4xIiwiZW1haWwiOiIiLCJjcmVhdGVkQXQiOiIyMDI1LTA3LTMxVDA3OjMwOjA3LjgxOFoiLCJpYXQiOjE3NTM5NDkzODAsImV4cCI6MTc1Mzk1MDEwMH0.9X-z2Jc86mKQU7wVxs-k8Mo4nwe_RIBPpbE-TOjkP_s




###
GET http://localhost:5000/api/v1/seeder/userSeeder
Content-Type: application/json



###
POST  http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{     "userName"    : "Admin1",
      "password" : "Admin123!"
}

###
POST  http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{     "userName"    : "TestAdmin1",
      "email" :  "Admin123@gmail.com",
      "password" :  "Admin123!",
      "phone" :  "0895606104423"
}



###
POST  http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{     "userName"    : "Admin1",
      "password" : "Admin123!"
}

###
GET  http://localhost:5000/api/v1/auth/fetch
Content-Type: application/json
Authorization: Bearer {{token}}





